### ISSUE TITLE
path issues in windows

### ISSUE THREAD

**Issue by mariodev** [modocache/django-generate-scaffold#1]
Inside file:
\generate_scaffold\utils\directories.py

add:

``` python
dir_suffix = dir_suffix.replace('/', os.path.sep)
```

to make the windows paths work properly.

**Comment by modocache** [comment]
Oh right! I imagine there are several portions that should be modified to accomodate a Windows setup. I'll fix this as soon as I can, or if you could submit a patch that'd be great!

**Comment by modocache** [comment]
Should be fixed in v0.0.5a0. Please reopen if you are still experiencing issues.
