### ISSUE TITLE
Scaffold doesn't generate all files

### ISSUE THREAD

**Issue by timonweb** [modocache/django-generate-scaffold#17]
I'm on Django 1.4.1,  following exactly instructions given in this video http://vimeo.com/42399125 on a clean install, my scaffold doesn't generate all files:
- it doesn't generate templates (it creates only a folder)
- it doesn't generate full boilerplate in views

Screenshot with command line output http://imagebin.org/230344

What can be wrong there?

**Comment by modocache** [comment]
It appears you're using Windows, is that correct? I believe this is due to issue #1... I don't have a Windows machine to properly test any changes this might involve, but I will try to fix this issue in the near future. Alternatively, if you could submit a pull request, that'd be stellar.

**Comment by modocache** [comment]
@timonweb Please try to `python setup.py install` the latest on the `develop` branch and let me know if the issue has been resolved.

**Comment by modocache** [comment]
Should be fixed in v0.0.5a0. Please reopen if you are still experiencing issues.

**Comment by timonweb** [comment]
I confirm. Fixed. Thank you.

**Comment by modocache** [comment]
:+1:
