### ISSUE TITLE
Support i18n

### ISSUE THREAD

**Issue by tokibito** [modocache/django-generate-scaffold#6]

**Comment by modocache** [comment]
確かに。Great idea.

**Comment by modocache** [comment]
@tokibito 今更感が半端ないんですが、とりあえず適当な日本語訳をつけてみました。出力されるテンプレートにも`trans`タグをつけておきました。抜けているところがあるかもしれないし、訳自体も曖昧な文章になっているかもしれないが、それらは修正してプル・リクエストしてくだされば:cool:

**Comment by tokibito** [comment]
すばらしい。試してみます。
